### ISSUE TITLE
Empty page when registering new user in iteration 0

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#1]
Browser: Google Chrome
Tried registering deliadally who has not been registered yet. Connect to deliadally Anchor wallet. Was expecting to be taken to the Register page but was presented with a blank page with only the Freeos icon at the top. See screenshot provided.
Please note: Currently in iteration 0 as the previous Iteration 2 has ended and no new iteration has been set yet.
![FreeOS App 6-25-2021 11-24-58 AM](https://user-images.githubusercontent.com/77765830/123345250-c5397b00-d5a9-11eb-92f3-f7920ab52b25.png)

**Comment by judytan21** [comment]
My understanding is that the user should not be able to use the frontend to do anything eg register, stake etc in iteration 0. I've asked Jerome n Tom if we should display an appropriate message such as "The AirClaim is unavailable at this time, please try later". Will let you know when I hear from them. Thanks.

**Comment by judytan21** [comment]
29/6/21 discussed this issue with JeromeK this morning. When refreshing a page, on detecting the Masterswitch has been turned off or in iteration 0 then present the page informing user that the AIrClaim system is currently unavailable. Thanks.

**Comment by stuartmcphersonflipmind** [comment]
#1 User Eject back to Welcome page if masterswitch turned off or no current iteration

**Comment by judytan21** [comment]
Retest 15/7/21 v0.8.4 When in iteration 0, a red msg box with 'The AirClaim is unavailable at this time, please try later' was displayed. 
![Freeos App 7-15-2021 1-18-29 PM](https://user-images.githubusercontent.com/77765830/125712899-87d906f5-eb7e-4369-b9ae-9f086128733c.png)

**Comment by judytan21** [comment]
Retest 15/7/21 v0.8.4 Part2. When masterswitch is off (value 0), the red msg box with 'The AirClaim is unavailable at this time, please try later' was displayed. Fixed.
![Freeos App 7-15-2021 1-39-57 PM](https://user-images.githubusercontent.com/77765830/125714724-a61d9e78-7cf0-4237-8542-80a192e2b580.png)
