### ISSUE TITLE
Was not prompted to stake after registering.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#11]
Pre-beta testing v0.8.3a Account type 'd' Staking reqmt 1 USDC
After connecting with the Proton wallet, proceed to register.
Registered successfully. However, on the Claims page, was not prompted to stake. Expecting to be prompted to stake.
![Screenshot_20210712-154533_Samsung Internet](https://user-images.githubusercontent.com/77765830/125366841-09f74b80-e3cb-11eb-9685-7af01b64218a.jpg)

**Comment by stuartmcphersonflipmind** [comment]
@judytan21 Thats quite an old version of the App, can you confirm you are getting the same issue with the latest version

**Comment by judytan21** [comment]
30/7/21 Pre-beta testing v0.9.0pb. Account type 'd', stake requirement = 10 FooBar. Prompted to stake. Fixed.

![image](https://user-images.githubusercontent.com/77765830/127592376-baa41f8c-a8f2-4d85-8c35-adeeb8f0ffd8.png)
