### ISSUE TITLE
Incorrect amount shown on pop up when unlocking OPTIONS

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#12]
Pre-beta tesing v0.8.3a
Selected the Unlock button to unlock 1% of the 50 locked OPTIONS.  A pop up was displayed showing 0.5 OPTIONS. Pop up was displayed briefly so was unable to take a snapshot of it. Expecting the unlock amount to be 1 OPTION instead of 0.5 OPTION. 
![Freeos App 7-12-2021 4-07-39 PM](https://user-images.githubusercontent.com/77765830/125367525-64dd7280-e3cc-11eb-9c9f-1990129df23b.png)
After unlocking, the balance of locked options was shown as 49 which is correct. 
![Freeos App 7-12-2021 4-08-24 PM](https://user-images.githubusercontent.com/77765830/125367638-9ce4b580-e3cc-11eb-8f57-05c34c2ad92b.png)

**Comment by stuartmcphersonflipmind** [comment]
@judytan21 So whats the calculation then? is it Rounded up?

**Comment by judytan21** [comment]
@stuartmcphersonflipmind yep, it should be rounded up to the nearest integer.

**Comment by stuartmcphersonflipmind** [comment]
Rounded up to the nearest integer in v0.8.6 now

**Comment by judytan21** [comment]
30/7/21 Pre-beta testing v0.9.0pb  Contracts: statsb, statscfgb
When unlocking 3%

**Comment by stuartmcphersonflipmind** [comment]
I was rounding on the decimal unvest value rather than the final result fixed in v0.9.1 now

**Comment by judytan21** [comment]
Hi Stuart  Quick ques. Would it be possible for you to hook up the latest
Airclaim Frontend (is it v0.9.2 ?) to the new qa env QA5 so i could test
the fixes for the pop up issues? Pls let me know asap.

Many thanks.
Jude

**Comment by judytan21** [comment]
11/8/21 v0.10.0pb - Retest in pre-beta using account freedao. Account bal=45000 points. Locked bal=39 points. Unlock 21% = 9 Points rounded. Pop up showing 9 points unlocked. After unlocking, Locked bal reduced to 30 points and account bal increased by 9 to 45009 points. Fixed.
