### ISSUE TITLE
Frontend re-register page and button incorrectly hooked up to reguser instead of reverify

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#13]
Pre-beta testing. v0.8.3a
Our 'v' community member was prompted to stake even tho' the staking requirement for type 'v' has been changed to 0 XUSDC.
JeromeK has discovered that this is due to the frontend re-register page and button being hooked up to 'reguser' and not 'reverify'. This is why our 'v' community member was unable to claim after Tom has changed the stake from 1XUSDC to 0 XUSDC

**Comment by stuartmcphersonflipmind** [comment]
Re-register set to reverify action v0.8.4

**Comment by judytan21** [comment]
Retested. 14/7/21 v0.8.4. QA4. After re-register,  alanappleton user record was updated from type 'e' 101 to type 'd' 100.
Fixed
