### ISSUE TITLE
On desktop, the hamburger menu is not shown on all pages all of the time.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#15]
Pre-beta v0.10.0 Link: https://p6mjg-5iaaa-aaaad-qamlq-cai.raw.ic0.app/
When running the AirClaim dapp on desktop, hamburger menu is automatically open after initial login. Subsequently, user will have to open the menu manually. Requirement is to have the hamburger menu open all of the time on all pages regardless on where the user is. 
![Freeos App 11-08-2021 12-41-07](https://user-images.githubusercontent.com/77765830/128952582-b198085f-3484-4e89-a69e-13bfba3ebe88.png)

**Comment by stuartmcphersonflipmind** [comment]
v0.10.1 has menu persisting open for route changes on Desktop only as for Mobile this would be annoying

**Comment by tommccann777** [comment]
This has been tested and performs successfully in 0.10.4
