### ISSUE TITLE
Minting gives wrong currency message

### ISSUE THREAD

**Issue by tommccann777** [FreeosDAO/airclaim_frontend#17]
In 0.10.4, when a user mints some BETA/FREEOS, the popup message says 'You have minted x POINTs'. This should instead be the name of the exchangeable currency i.e BETA or FREEOS.

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.10.5

**Comment by judytan21** [comment]
9/11/21 v0.11.0 Mint 10 POINTs to BETA, Pop up is now showing the correct BETA currency. Fixed. 
See screenshots below:
![Freeos App 09-11-2021 10-35-05](https://user-images.githubusercontent.com/77765830/140823062-15295d7f-9be4-40a2-8977-14a9ba571251.png)

![20211109_103626](https://user-images.githubusercontent.com/77765830/140823842-c2026719-32fa-4b30-8f30-abf64b4c52bf.jpg)
