### ISSUE TITLE
Incorrect End of AirClaim message

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#18]
AirClaim Pre-beta v0.10.10-qa5 https://p6mjg-5iaaa-aaaad-qamlq-cai.raw.ic0.app/   
Test priority 2 feature: 'Next claim beginning' needs to have messaging about last interation / end of airclaim. e.g. 'The final claim ends in ... 
On the final iteration in QA5, the Claims page was correctly showing the Final Claim ends in 21 hrs 26mins. See attached screenshot. 
![unknown-png -1136×1250- 22-09-2021 16-37-04](https://user-images.githubusercontent.com/77765830/134284427-fe573ab2-86e9-4d8b-93f9-5492744a3930.png)

However, at the end of the last iteration, it counted down by minute and displayed the message 'Airclaim  Not Started'. Expecting msg 'AirClaim has now Closed'. See screenshot below
![unknown-png -1176×1194- 22-09-2021 16-51-08](https://user-images.githubusercontent.com/77765830/134285360-19fa4cdf-cb1f-4c83-ab11-fb1d1b16dda4.png):

**Comment by tommccann777** [comment]
Thanks Stuart

Tom

**Comment by judytan21** [comment]
9/11/21 Retested AirClaim v0.11.0-pb4 Link:https://p6mjg-5iaaa-aaaad-qamlq-cai.raw.ic0.app/claim. Correct message is now displayed. See attached screenshot. Fixed.

![Freeos App 09-11-2021 10-32-38](https://user-images.githubusercontent.com/77765830/140824661-68798b9d-1718-48b1-b630-41f464954f62.png)
