### ISSUE TITLE
Claiming within the last hour of current iteration - Next Claim info missing

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#2]
When claiming within the last hour of the current iteration, there was nothing shown under Next Claim. See attached screenshot. I've discussed this with JeromeK this morning and he has asked me to log it as an issue. He will have a chat with you about extending the Next Claim by an hour. 
![FreeOS App 6-25-2021 12-02-57 PM](https://user-images.githubusercontent.com/77765830/123363550-e5c3fe00-d5c6-11eb-80f7-272037e63815.png)

**Comment by stuartmcphersonflipmind** [comment]
Fix made to show minutes remaining when under an hour v0.5.1

**Comment by judytan21** [comment]
25/6/21 Retested. Next Claim now showing in mins. Fixed. 
[FreeOS App 6-25-2021 4-08-28 PM](https://user-images.githubusercontent.com/77765830/123368423-e57c3080-d5cf-11eb-8655-add44ee7c1bb.png)

**Comment by judytan21** [comment]
29/6/21 Reopen issue as JeromeK has requested for Next Claim to be shown in hours and mins. Not just the remaining mins when  under an hour. Cheers.

**Comment by stuartmcphersonflipmind** [comment]
Mins now added to Hrs in version 0.7.6

**Comment by judytan21** [comment]
14/7/21 v0.8.4 Retest. On Claims page, Next Claim is now showing hours and mins. Fixed.
![Freeos App 7-14-2021 11-03-20 AM](https://user-images.githubusercontent.com/77765830/125536796-dee32694-9db3-43b5-8421-d7729883247f.png)
