### ISSUE TITLE
AIRKEY icon not displayed

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#3]
User powderblue has an AIRKEY but no AIRKEY icon was displayed. Expecting an AIRKEY icon to be visible for accounts with an AIRKEY.

![FreeOS Claim](https://user-images.githubusercontent.com/77765830/123581340-c8459d00-d82f-11eb-9660-4519a89b5767.png)

**Comment by tommccann777** [comment]
My understanding is that we created the AIRKEY icon to help in our own testing but that it was never meant for production. Best check with Jerome though.

**Comment by judytan21** [comment]
Display of AIRKEY icon was in the miro ux flow.

**Comment by judytan21** [comment]
29/6/21-discussed the display of AIRKEY icon with JefromeK this morning. Can you please make the AIRKEY icon as an environmental variable which can be turned off for production?

**Comment by stuartmcphersonflipmind** [comment]
![image](https://user-images.githubusercontent.com/58194035/124839718-6b8b7480-dfdd-11eb-9f70-01b1bc63841d.png)

**Comment by stuartmcphersonflipmind** [comment]
The above icon should display if AirKey balance > 0 now in v0.7.7

**Comment by judytan21** [comment]
9/7/21 v0.8.1 - Retested with powderblue who has 1 AIRKEY but AIRKEY icon was not visible. See screenshot.
![Freeos App 7-9-2021 4-58-08 PM](https://user-images.githubusercontent.com/77765830/125025499-dec4e180-e0d6-11eb-9d9c-f33a4157bc4e.png)

**Comment by stuartmcphersonflipmind** [comment]
This is fixed now v0.8.3

**Comment by judytan21** [comment]
12/7/21 v0.8.3 - Retested with powderblue who has 1 AIRKEY and AIRKEY icon is now visible. Fixed.
![Freeos App 7-12-2021 2-33-24 PM](https://user-images.githubusercontent.com/77765830/125222574-5f295380-e31e-11eb-8fb2-de3633de8f3c.png)
