### ISSUE TITLE
Display of OPTIONS and FREEOS amounts overlapped

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#4]
Converted 1.5250 OPTIONS to FREEOS for powderblueOPTIONS balance = 198.4750 and FREEOS balance = 1.5250 which is correct.  However, display of the OPTIONS and FREEOS amounts overlapped on the account summary.
 
![FreeOS Displayed Amts Overlap](https://user-images.githubusercontent.com/77765830/123734418-6c434d00-d8f1-11eb-990a-b7972b84c25d.png)

**Comment by stuartmcphersonflipmind** [comment]
Reduced the Size of the Text here

**Comment by judytan21** [comment]
2/7/21 Retested in v0.6.7 - the amounts looks good but on selecting the convert icon on the Claims Page, was taken to the Welcome screen instead of the Convert page (ref. Issue#7)

**Comment by stuartmcphersonflipmind** [comment]
Closing as this fixed & also setup under another issue #7
