### ISSUE TITLE
Unvest pop up not displayed after unvesting

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#5]
v0.6.3 QA4 Iteration 6 user ellaevery
After unvesting successfully, was expecting the Unvest pop up "Excellent! You've unvested 4 OPTIONS" to be displayed. 
(ref miro ux flow) but pop up was not displayed.

**Comment by stuartmcphersonflipmind** [comment]
Unvest Confirm popup added now at v0.6.8

**Comment by judytan21** [comment]
Retest 14/7/21 v0.8.4 - Unvest confirmation pop up appeared. However, the unvest amount shown was 4.55 OPTIONS. Expecting the amount shown to be rounded up to the nearest integer. Will close this issue as the rounding issue already logged as issue#12.
