### ISSUE TITLE
Pop up not displayed after Claiming.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#6]
After claiming was expecting pop up "Woohoo! You've earned 100 OPTIONS" (ref miro UX flow) to be displayed but pop up was not displayed.

**Comment by stuartmcphersonflipmind** [comment]
Claim Confirm popup added now at v0.6.8

**Comment by judytan21** [comment]
Retest 14/7/21 v0.8.4 - Claim pop up appeared. However, please change 'Wahoo!' to 'Woohoo' (JeromeK's preference).

**Comment by stuartmcphersonflipmind** [comment]
Changed to Woohoo v0.8.6 closing
