### ISSUE TITLE
Convert page was not presented on selecting the Convert icon on the Claims page

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#7]
v0.6.7 QA4 https://epic-poincare-d23849.netlify.app/
On the Claims page, selected the Convert icon and was taken to the Welcome page. Was expecting the Convert page to be presented.
![Freeos App 7-2-2021 3-04-08 PM](https://user-images.githubusercontent.com/77765830/124214685-bb35f000-db46-11eb-8fac-61050db1a170.png)
 ![Freeos App 7-2-2021 3-05-11 PM](https://user-images.githubusercontent.com/77765830/124214779-e15b9000-db46-11eb-8276-022f5799f9f0.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.6.8

**Comment by judytan21** [comment]
9/7/21 v0.8.1 On the Claims page, selected the Convert icon and the Convert page was presented. Fixed.
![Freeos App 7-9-2021 5-08-11 PM](https://user-images.githubusercontent.com/77765830/125026243-40d21680-e0d8-11eb-8642-5f9a95958389.png)
