### ISSUE TITLE
Unstake button was enabled when Staked amount is 0 XPR

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/airclaim_frontend#9]
This issue was found during Alpha testing for NZ - v0.6.4n freeosn 
In iteration 1, the staking requirement for user deliadally type 'd' was 0 XPR. Was able to Claim without staking.
On the Stake Requirements page, it was correctly showing as 0 XPR. However, the Unstake button was enabled. 
Expecting Unstake button to be enabled only when the staked amount is greater than 0 XPR.
On selecting Unstake, the backend catches it and an assertion error "user does not have a staked amount" was correctly displayed.

**Comment by judytan21** [comment]
Screenshot of Stake requirements page
![Freeos App 7-6-2021 2-13-21 PM](https://user-images.githubusercontent.com/77765830/124532331-6e168e80-de64-11eb-847d-5cac5b7d6a9b.png)

**Comment by stuartmcphersonflipmind** [comment]
Closing as this fixed & also setu under another issue #7

**Comment by stuartmcphersonflipmind** [comment]
Ok there was a Bug with and you should of been able to get to this page, because the Stake page link should of been hidden Ive fixed this also hidden the Unstaking section just incase a user still finds the Stake page

**Comment by judytan21** [comment]
11/8/21 This is no longer applicable as the implementation has changed. The stake/unstake function will be displayed where applicable in the menu for user to stake/unstake. JK/Tom managed to get someone with account type 'v' in beta testing. Closing issue.
